stages:
  - validate

conftest_scan:
  image: openpolicyagent/conftest
  stage: validate
  script:
    - cd terraform
    - terraform init
    - terraform plan -out=tfplan.binary
    - terraform show -json tfplan.binary > tfplan.json
    - conftest test tfplan.json --policy policy
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

