image: docker:latest

services:
  - docker:dind

stages:
  - validate
  - build
  - scan
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TRIVY_SEVERITY: "HIGH,CRITICAL"

before_script:
  - docker info
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

validate-config:
  stage: validate
  script:
    - docker compose config
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

build-image:
  stage: build
  script:
    - docker build -t rogerramossilva/myapp:$CI_COMMIT_SHORT_SHA .
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

security-scan:
  stage: scan
  before_script:
    - mkdir -p ./bin
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
    - export PATH="$PATH:$(pwd)/bin"
  script:
    - docker build -t rogerramossilva/myapp:$CI_COMMIT_SHORT_SHA .
    - ./bin/trivy image --exit-code 0 --severity MEDIUM,HIGH,CRITICAL rogerramossilva/myapp:$CI_COMMIT_SHORT_SHA

secure-deploy:
  stage: deploy
  script:
    - echo "🚀 Deploy seguro realizado!"
  environment:
    name: production
    url: https://example.com

