kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-read-nodes
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: rbac-lab
roleRef:
  kind: ClusterRole
  name: read-nodes
  apiGroup: rbac.authorization.k8s.io

